.PHONY: dummy clean distclean testclean docclean doc cssclean webpacksass .FORCE

dummy:
	@echo "'make' is no longer used for deployment. See 'doc/intro/install.rst'"

clean:
	-find . -name __pycache__ -print0 | xargs -0 rm -rf
	-find . -name "*.pyc" -print0 | xargs -0 rm -rf
	-find . -name "*.egg-info" -print0 | xargs -0 rm -rf
	-find . -name ".*.sw?" -print0 | xargs -0 rm -rf

distclean:
	-rm -rf build
	-rm -rf dist

testclean: clean
	-rm core
	-rm *.stats
	-rm python/nav/web/static/js/package-lock.json
	-rm -rf .tox

docclean:
	-rm -rf doc/_build

doc: doc/reference/alerttypes.rst

doc/reference/alerttypes.rst: .FORCE
	python3 doc/exts/alerttypes.py > $@

.env: .FORCE
	echo "# This file was generated by 'make .env'" > .env
	echo "UID=$(shell id -u)" >> .env
	echo "GID=$(shell id -g)" >> .env

cssclean:
	-rm -rf python/nav/web/static/css

webpacksass: cssclean
	-(cd python/nav/web/static/js && npm install && npm run build:sass:prod)
	-echo "\n *** Manually disable running of setuptool's build_sass command and sass-watch.sh script. Then run docker-compose up to test web app with CSS files built by Webpack. *** \n"

.FORCE:
